# Generated by Django 5.1.6 on 2025-03-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('Studio', 'Studio'), ('Villa', 'Villa'), ('Luxury House', 'Luxury House'), ('Standard House', 'Standard House')], max_length=50)),
                ('total_land_dimension', models.CharField(max_length=20)),
                ('guest_room_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('bedroom_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('living_room_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('garage_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('Bathroom_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('kitchen_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('balcony_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('dining_room_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('foyer_dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
